# Generated by Django 2.1.1 on 2018-11-15 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal_quadro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='pessoal_quadro.Pessoa')),
                ('numero_contribuite', models.CharField(max_length=20)),
                ('numero_caixa_social', models.CharField(max_length=20)),
                ('nivel_academico', models.CharField(choices=[(' ', 'Nivel Academico'), ('Ensino Medio', 'Ensino Medio'), ('Basharele', 'Basharele'), ('Licenciado', 'Licenciado'), ('Mestrado', 'Mestrado'), ('Phd', 'Phd')], max_length=20)),
                ('curso', models.CharField(max_length=30)),
                ('funcao', models.CharField(blank=True, max_length=30, null=True)),
                ('patente', models.CharField(choices=[(' ', 'Patente do Agente'), ('Agente-1ª-Classe', 'Agente 1ª Classe'), ('Agente-2ª-Classe', 'Agente 2ª Classe'), ('Agente-3ª-Classe', 'Agente 3ª Classe'), ('1ª-Subchefe', '1ª subchefe'), ('2ª-Subchefe', '2ª Subchefe'), ('3ª-Subchefe', '3ª Subchefe'), ('Ispector', 'Ispector'), ('Ispector-chefe', 'Ispector-chefe'), ('Intendente', 'Intendente'), ('Subi-chefe', 'Subi-chefe'), ('Superintendente', 'Superintendente'), ('Subi-comandante', 'Subi-comandante'), ('Comisario', 'Comisario'), ('Comandante', 'Comandante')], max_length=25)),
                ('categoria', models.CharField(choices=[(' ', 'Classe da Patente'), ('Officias', 'Officias'), ('Officias-Subalterno', 'Officias-Subalterno'), ('Agente', 'Agentes')], max_length=20)),
                ('numero_agente', models.IntegerField(unique='true')),
                ('nip', models.CharField(blank=True, default='Não indetificado', max_length=20, null=True)),
                ('data_igresso', models.CharField(max_length=20)),
                ('foto_fardado', models.ImageField(blank=True, default='user.jpg', null=True, upload_to='%Y/')),
                ('foto_civil', models.ImageField(blank=True, default='user.jpg', null=True, upload_to='%Y/')),
            ],
        ),
    ]
