# Generated by Django 2.1.1 on 2018-11-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal_quadro', '0003_baixa_despromocao_feria_nomiacao_cargo_orgao_reforma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='casa_numero',
            field=models.CharField(default='sem endereço', max_length=30, null=True),
        ),
    ]
