# Generated by Django 2.1.1 on 2018-11-21 01:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal_quadro', '0004_auto_20181115_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patentiamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='pessoal_quadro.Agente')),
                ('dispacho', models.CharField(default='Sem dispacho', max_length=20, null=True)),
                ('data', models.CharField(default=datetime.date(2018, 11, 21), max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='orgao',
            name='localizacao',
        ),
        migrations.RemoveField(
            model_name='orgao',
            name='unidade',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='nacionalidade',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='naturalidade',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='passporte',
        ),
        migrations.AlterField(
            model_name='agente',
            name='categoria',
            field=models.CharField(choices=[('Officias-Generais', 'Officias-Generais'), ('Officias-Superiores', 'Officias-Superiores'), ('Officias-Subalterno', 'Officias-Subalterno'), ('Officias-Intermediarios', 'Intermediarios'), ('Praças', 'Praças')], max_length=20),
        ),
        migrations.AlterField(
            model_name='agente',
            name='nivel_academico',
            field=models.CharField(choices=[('8ªClasse', '8ªClasse'), ('12ªClasse', '12ªClasse'), ('Têcnico Medio', 'Têcnico Medio'), ('Licenciado', 'Licenciado'), ('Mestre', 'Mestre'), ('Doutor', 'Doutor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='agente',
            name='patente',
            field=models.CharField(choices=[('Agente-1ª-Classe', 'Agente 1ª Classe'), ('Agente-2ª-Classe', 'Agente 2ª Classe'), ('Agente-3ª-Classe', 'Agente 3ª Classe'), ('1ª-Subchefe', '1ª subchefe'), ('2ª-Subchefe', '2ª Subchefe'), ('3ª-Subchefe', '3ª Subchefe'), ('Ispector', 'Ispector'), ('Ispector-chefe', 'Ispector-chefe'), ('Intendente', 'Intendente'), ('Subi-chefe', 'Subi-chefe'), ('Superintendente', 'Superintendente'), ('Subi-comandante', 'Subi-comandante'), ('Comisario', 'Comisario'), ('Comandante', 'Comandante')], max_length=25),
        ),
        migrations.AlterField(
            model_name='baixa',
            name='data_entrada',
            field=models.CharField(default=datetime.date(2018, 11, 21), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='baixa',
            name='motivo',
            field=models.CharField(choices=[('Transferencia', 'Transferencia'), ('Acidente', 'Acidente'), ('Valecimento', 'Valecimento'), ('Dificiencia Contraida', 'Dificiencia Contraida'), ('Outro', 'Outro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='despromocao',
            name='motivo',
            field=models.CharField(choices=[('Indisciplina', 'Indisciplina'), ('Desvio de informação', 'Desvio de informação'), ('Omicido', 'Omicido'), ('Calunia e Defamação', 'Calunia e Defamação'), ('Outras', 'Outras')], max_length=30),
        ),
        migrations.AlterField(
            model_name='nomiacao_cargo',
            name='categoria',
            field=models.CharField(choices=[('Graduação', 'Graduação'), ('Promoção', 'Promoção')], max_length=100),
        ),
        migrations.AlterField(
            model_name='nomiacao_cargo',
            name='tipo',
            field=models.CharField(choices=[('Indicação', 'Indicação'), ('Nomiação', 'Nomiação')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='data_colocacao',
            field=models.CharField(blank=True, default=datetime.date(2018, 11, 21), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(blank=True, default='cpl@gmail.com', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='estado_civil',
            field=models.CharField(choices=[('Solteiro (a)', 'solteiro (a)'), ('Casado (a)', 'casado (a)'), ('Divorciado (a)', 'Divorciado (a)'), ('Viuvo (a)', 'viuvo (a)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=12),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='provincia',
            field=models.CharField(choices=[('Luanda', 'Luanda'), ('Bengo', 'Bengo'), ('Benguela', 'Benguela'), ('Bié', 'Bié'), ('Cabinda', 'Cabinda'), ('Cunene', 'Cunene'), ('Huambo', 'Huambo'), ('Huila', 'Huila'), ('Kwando kubango', 'Kwando kubango'), ('Kwanza norte', 'Kwanza norte'), ('Kwanza sul', 'Kwanza sul'), ('Lunda Norte', 'Lunda Norte'), ('Lunda sul', 'Lunda sul'), ('Moxico', 'Moxico'), ('Namibe', 'Namibe'), ('Uige', 'Uige'), ('Zaire', 'Zaire')], max_length=25),
        ),
        migrations.AlterField(
            model_name='reforma',
            name='data',
            field=models.CharField(default=datetime.date(2018, 11, 21), max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reforma',
            name='motivo',
            field=models.CharField(blank=True, choices=[('Acidente', 'Acidente'), ('Valecimento', 'Valecimento'), ('Dificiencia Contraida', 'Dificiencia Contraida'), ('Outro', 'Outro')], default='Outro', max_length=100, null=True),
        ),
    ]
