# Generated by Django 2.1.1 on 2018-11-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal_quadro', '0005_auto_20181121_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgao',
            name='orgao_colocacao',
            field=models.CharField(choices=[('Comando-Geral', 'Comando-Geral'), ('Comando Provincial', 'Comando Provincial'), ('Comando Distrito', 'Comando Distrito')], default='cpl', max_length=60, null=True),
        ),
    ]
