# Generated by Django 2.1.1 on 2018-11-21 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal_quadro', '0006_auto_20181121_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='telefone_parente',
        ),
    ]
