# Generated by Django 2.1.1 on 2018-11-24 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal_quadro', '0007_remove_pessoa_telefone_parente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='categoria',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='agente',
            name='nivel_academico',
            field=models.CharField(choices=[('8ªClasse', '8ª Classe'), ('12ªClasse', '12ª Classe'), ('13ªClasse', '13ª Classe'), ('Têcnico Medio', 'Têcnico Medio'), ('Licenciado', 'Licenciado'), ('Mestre', 'Mestre'), ('Doutor', 'Doutor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='agente',
            name='patente',
            field=models.CharField(choices=[('Agente-1ª-Classe', 'Agente 1ª Classe'), ('Agente-2ª-Classe', 'Agente 2ª Classe'), ('Agente-3ª-Classe', 'Agente 3ª Classe'), ('1ª-Subchefe', '1ª subchefe'), ('2ª-Subchefe', '2ª Subchefe'), ('3ª-Subchefe', '3ª Subchefe'), ('Ispector', 'Ispector'), ('Subinspetor', 'Sub-inspetor'), ('Ispector-chefe', 'Ispector-chefe'), ('Intendente', 'Intendente'), ('Superintendente', 'Superintendente'), ('Subcomissário', 'Subcomissário'), ('Comissario-geral', 'Comissario geral'), ('Comissario-chefe', 'Comissario chefe')], max_length=25),
        ),
        migrations.AlterField(
            model_name='baixa',
            name='data_entrada',
            field=models.CharField(default=datetime.date(2018, 11, 24), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='data_colocacao',
            field=models.CharField(blank=True, default=datetime.date(2018, 11, 24), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patentiamento',
            name='data',
            field=models.CharField(default=datetime.date(2018, 11, 24), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reforma',
            name='data',
            field=models.CharField(default=datetime.date(2018, 11, 24), max_length=10, null=True),
        ),
    ]
