# Generated by Django 2.1.1 on 2018-12-04 02:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal_quadro', '0010_auto_20181130_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='patente',
            field=models.CharField(choices=[('Agente-1ª-Classe', 'Agente 1ª Classe'), ('Agente-2ª-Classe', 'Agente 2ª Classe'), ('Agente-3ª-Classe', 'Agente 3ª Classe'), ('1ª-Subchefe', '1ª subchefe'), ('2ª-Subchefe', '2ª Subchefe'), ('3ª-Subchefe', '3ª Subchefe'), ('Ispector', 'Ispector'), ('Sub-inspetor', 'Sub-inspetor'), ('Inspector-chefe', 'Inspector-chefe'), ('Intendente', 'Intendente'), ('Superintendente', 'Superintendente'), ('Sub-comissário', 'Sub-comissário'), ('Comissario-geral', 'Comissario geral'), ('Comissario-chefe', 'Comissario chefe')], max_length=25),
        ),
        migrations.AlterField(
            model_name='baixa',
            name='data_entrada',
            field=models.CharField(default=datetime.date(2018, 12, 4), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='despromocao',
            name='suspensao',
            field=models.CharField(choices=[('outro', 'outro'), ('3 Mes de Cadeia', '3 Mes de Cadeia'), ('Prestar serviço de Limpeza', 'Prestar serviço de Limpeza'), ('2 Ano de Cadeia', '2 Ano de Cadeia'), ('Retirada da Patente', 'Retirada da Patente'), ('1 Mes de Cadeia', '1 Mes de Cadeia'), ('2 Mes de Cadeia', '2 Mes de Cadeia'), ('1 Ano de Cadeia', '1 Ano de Cadeia')], max_length=500),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='data_colocacao',
            field=models.CharField(blank=True, default=datetime.date(2018, 12, 4), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patentiamento',
            name='data',
            field=models.CharField(default=datetime.date(2018, 12, 4), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reforma',
            name='data',
            field=models.CharField(default=datetime.date(2018, 12, 4), max_length=10, null=True),
        ),
    ]
