# Generated by Django 2.1.1 on 2018-12-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal_quadro', '0011_auto_20181204_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despromocao',
            name='suspensao',
            field=models.CharField(choices=[('2 Ano de Cadeia', '2 Ano de Cadeia'), ('1 Mes de Cadeia', '1 Mes de Cadeia'), ('1 Ano de Cadeia', '1 Ano de Cadeia'), ('outro', 'outro'), ('Retirada da Patente', 'Retirada da Patente'), ('Prestar serviço de Limpeza', 'Prestar serviço de Limpeza'), ('3 Mes de Cadeia', '3 Mes de Cadeia'), ('2 Mes de Cadeia', '2 Mes de Cadeia')], max_length=500),
        ),
    ]
