# Generated by Django 2.1.1 on 2018-12-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal_quadro', '0015_auto_20181208_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despromocao',
            name='suspensao',
            field=models.CharField(choices=[('2 Ano de Cadeia', '2 Ano de Cadeia'), ('2 Mes de Cadeia', '2 Mes de Cadeia'), ('Prestar serviço de Limpeza', 'Prestar serviço de Limpeza'), ('Retirada da Patente', 'Retirada da Patente'), ('1 Mes de Cadeia', '1 Mes de Cadeia'), ('3 Mes de Cadeia', '3 Mes de Cadeia'), ('outro', 'outro'), ('1 Ano de Cadeia', '1 Ano de Cadeia')], max_length=500),
        ),
    ]
