# Generated by Django 2.1.1 on 2019-01-30 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal_quadro', '0019_auto_20181227_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='nivel_academico',
            field=models.CharField(choices=[('9ªClasse', '9ª Classe'), ('12ªClasse', '12ª Classe'), ('13ªClasse', '13ª Classe'), ('Têcnico Medio', 'Têcnico Médio'), ('Licenciado', 'Licenciado'), ('Mestre', 'Mestre'), ('Doutor', 'Doutor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='agente',
            name='patente',
            field=models.CharField(choices=[('Agente-1ª-Classe', 'Agente 1ª Classe'), ('Agente-2ª-Classe', 'Agente 2ª Classe'), ('Agente-3ª-Classe', 'Agente 3ª Classe'), ('1ª-Subchefe', '1ª subchefe'), ('2ª-Subchefe', '2ª Subchefe'), ('3ª-Subchefe', '3ª Subchefe'), ('Inspector', 'Inspector'), ('Sub-inspetor', 'Sub-inspetor'), ('Inspector-chefe', 'Inspector-chefe'), ('Intendente', 'Intendente'), ('Superintendente', 'Superintendente'), ('Sub-comissário', 'Sub-comissário'), ('Comissário-geral', 'Comissário geral'), ('Comissário-chefe', 'Comissário chefe')], max_length=60),
        ),
        migrations.AlterField(
            model_name='baixa',
            name='data_entrada',
            field=models.CharField(default=datetime.date(2019, 1, 30), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='baixa',
            name='motivo',
            field=models.CharField(choices=[('Transferência', 'Transferência'), ('Acidente', 'Acidente'), ('Dificiência Contraída', 'Dificiência Contraída'), ('Outro', 'Outro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='despromocao',
            name='suspensao',
            field=models.CharField(choices=[('1 Ano de Cadeia', '1 Ano de Cadeia'), ('Prestar serviço de Limpeza', 'Prestar serviço de Limpeza'), ('1 Mes de Cadeia', '1 Mes de Cadeia'), ('outro', 'outro'), ('3 Mes de Cadeia', '3 Mes de Cadeia'), ('2 Mes de Cadeia', '2 Mes de Cadeia'), ('Retirada da Patente', 'Retirada da Patente'), ('2 Ano de Cadeia', '2 Ano de Cadeia')], max_length=500),
        ),
        migrations.AlterField(
            model_name='nomiacao_cargo',
            name='cargo',
            field=models.CharField(choices=[('Delegado', 'Delegado'), ('Investigador', 'Investigador'), ('Auxiliar de Investigador', 'Auxiliar de Investigador'), ('Escrivão', 'Escrivão'), ('Perito Criminal', 'Perito Criminal'), ('perito Medico-Legista', 'perito Medico-Legista')], max_length=20),
        ),
        migrations.AlterField(
            model_name='nomiacao_cargo',
            name='tipo',
            field=models.CharField(choices=[('Indicação', 'Indicação'), ('Nomeação', 'Nomeação')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='data_colocacao',
            field=models.CharField(blank=True, default=datetime.date(2019, 1, 30), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='orgao_colocacao',
            field=models.CharField(choices=[('Comando-Geral', 'Comando-Geral'), ('Comando Provincial de Luanda', 'Comando Provincial de luanda'), ('Comando Provincial do Huambo', 'Comando Provincial do Huambo'), ('Comando Provincial do Bengo', 'Comando Provincial do Bengo'), ('Comando Provincial do Kuanza Sul', 'Comando Provincial do Kuanza Sul'), ('Comando Provincial do Kuanza Norte', 'Comando Provincial do Kuanza Norte'), ('Comando Provincial da Huila', 'Comando Provincial da Huila'), ('Comando Provincial da Lunda Norte', 'Comando Provincial da Lunda Norte'), ('Comando Provincial do Cunene', 'Comando Provincial do Cunene'), ('Comando Provincial do Uige', 'Comando Provincial do Uige'), ('Comando Provincial de Cabinda', 'Comando Provincial de Cabinda'), ('Comando Provincial do Namibe', 'Comando Provincial do Namibe'), ('Comando Provincial do Moxico', 'Comando Provincial do Moxico'), ('Comando Provincial do Bie', 'Comando Provincial do Bie'), ('Comando Provincial de Benguela', 'Comando Provincial de Benguela'), ('Comando Provincial do Malanje', 'Comando Provincial de Malanje'), ('Comando Provincial do Zaire', 'Comando Provincial do Zaire')], default='cpl', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='patentiamento',
            name='data',
            field=models.CharField(default=datetime.date(2019, 1, 30), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=12),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='provincia',
            field=models.CharField(choices=[('Luanda', 'Luanda'), ('Bengo', 'Bengo'), ('Benguela', 'Benguela'), ('Bié', 'Bié'), ('Cabinda', 'Cabinda'), ('Cunene', 'Cunene'), ('Huambo', 'Huambo'), ('Huila', 'Huila'), ('Cuando kubango', 'Cuando kubango'), ('Cuanza norte', 'Cuanza norte'), ('Cuanza sul', 'Cuanza sul'), ('Lunda Norte', 'Lunda Norte'), ('Lunda sul', 'Lunda sul'), ('Malange', 'Malange'), ('Moxico', 'Moxico'), ('Namibe', 'Namibe'), ('Uige', 'Uige'), ('Zaire', 'Zaire')], max_length=25),
        ),
        migrations.AlterField(
            model_name='reforma',
            name='data',
            field=models.CharField(default=datetime.date(2019, 1, 30), max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reforma',
            name='motivo',
            field=models.CharField(blank=True, choices=[('Acidente', 'Acidente'), ('Dificiência Contraída', 'Dificiência Contraída'), ('Outro', 'Outro')], default='Outro', max_length=100, null=True),
        ),
    ]
