# Generated by Django 2.1.1 on 2019-02-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal_quadro', '0035_auto_20190221_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baixa',
            old_name='motivo',
            new_name='motivo_baixa',
        ),
        migrations.AlterField(
            model_name='despromocao',
            name='suspensao',
            field=models.CharField(choices=[('3 Mes de Cadeia', '3 Mes de Cadeia'), ('outro', 'outro'), ('1 Ano de Cadeia', '1 Ano de Cadeia'), ('2 Mes de Cadeia', '2 Mes de Cadeia'), ('Prestar serviço de Limpeza', 'Prestar serviço de Limpeza'), ('1 Mes de Cadeia', '1 Mes de Cadeia'), ('Retirada da Patente', 'Retirada da Patente'), ('2 Ano de Cadeia', '2 Ano de Cadeia')], max_length=500),
        ),
    ]
