# Generated by Django 2.2.1 on 2019-05-04 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal_quadro', '0041_auto_20190501_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baixa',
            name='data_entrada',
            field=models.CharField(default=datetime.date(2019, 5, 4), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='baixa',
            name='dispacho',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='despromocao',
            name='dispacho',
            field=models.CharField(default='Sem despacho', max_length=18),
        ),
        migrations.AlterField(
            model_name='despromocao',
            name='suspensao',
            field=models.CharField(choices=[('1 Ano de Cadeia', '1 Ano de Cadeia'), ('2 Ano de Cadeia', '2 Ano de Cadeia'), ('3 Mes de Cadeia', '3 Mes de Cadeia'), ('Prestar serviço de Limpeza', 'Prestar serviço de Limpeza'), ('2 Mes de Cadeia', '2 Mes de Cadeia'), ('outro', 'outro'), ('Retirada da Patente', 'Retirada da Patente'), ('1 Mes de Cadeia', '1 Mes de Cadeia')], max_length=500),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='dispacho',
            field=models.CharField(default='Sem despacho', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='nomiacao_cargo',
            name='dispacho',
            field=models.CharField(default='Sem despacho', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='data_colocacao',
            field=models.CharField(blank=True, default=datetime.date(2019, 5, 4), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='dispacho',
            field=models.CharField(blank=True, default='Sem despacho', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='patentiamento',
            name='data',
            field=models.CharField(default=datetime.date(2019, 5, 4), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patentiamento',
            name='dispacho',
            field=models.CharField(default='Sem despacho', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='reforma',
            name='data',
            field=models.CharField(default=datetime.date(2019, 5, 4), max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reforma',
            name='dispacho',
            field=models.CharField(default='Sem despacho', max_length=18, null=True),
        ),
    ]
