# Generated by Django 2.2.1 on 2019-05-08 00:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal_quadro', '0042_auto_20190504_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baixa',
            name='data_entrada',
            field=models.CharField(default=datetime.date(2019, 5, 8), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='despromocao',
            name='suspensao',
            field=models.CharField(choices=[('2 Mes de Cadeia', '2 Mes de Cadeia'), ('3 Mes de Cadeia', '3 Mes de Cadeia'), ('1 Ano de Cadeia', '1 Ano de Cadeia'), ('1 Mes de Cadeia', '1 Mes de Cadeia'), ('outro', 'outro'), ('2 Ano de Cadeia', '2 Ano de Cadeia'), ('Retirada da Patente', 'Retirada da Patente'), ('Prestar serviço de Limpeza', 'Prestar serviço de Limpeza')], max_length=500),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='pena',
            field=models.CharField(choices=[('Repreensão simples', 'Repreensão simples'), ('Repreensão registada', 'Repreensão registada'), ('Patrulha, guarda e piquete até 5 mês', 'Patrulha, guarda e piquetes até 5 mês'), ('Rondas, guarda e piquete até 5 mês', 'Ronda, guarda e piquetes até 5 mês'), ('Multa correspondente a 1 dia', 'Multa correspondente a 1 dia'), ('Multa correspondente a 20 dias', 'Multa correspondente a 20 dias'), ('Detenção até 25 dias', 'Detenção até 25 dias'), ('Prisão até 15 dias', 'Prisão até 15 dias'), ('Prisão até 30 dias', 'Prisão até 30 dias'), ('Prisão até 45 dias', 'Prisão até 45 dias'), ('Despromoção do Cargo', 'Despromoção do Cargo')], max_length=800),
        ),
        migrations.AlterField(
            model_name='nomiacao_cargo',
            name='cargo',
            field=models.CharField(choices=[('Delegado', 'Delegado'), ('Investigador', 'Investigador'), ('Auxiliar de Investigador', 'Auxiliar de Investigador'), ('Escrivão', 'Escrivão'), ('Perito Criminal', 'Perito Criminal'), ('perito Medico-Legista', 'perito Medico-Legista'), ('Delegado', 'Delegado')], max_length=200),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='data_colocacao',
            field=models.CharField(blank=True, default=datetime.date(2019, 5, 8), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patentiamento',
            name='data',
            field=models.CharField(default=datetime.date(2019, 5, 8), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reforma',
            name='data',
            field=models.CharField(default=datetime.date(2019, 5, 8), max_length=10, null=True),
        ),
    ]
