# Generated by Django 2.2.1 on 2019-05-15 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal_quadro', '0043_auto_20190508_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='area_formacao',
            field=models.CharField(choices=[('Ciência Sociais', 'Ciência Sociais'), ('Saude', 'Saude'), ('Direito', 'Direito'), ('Economia', 'Economia'), ('Letras', 'Letras'), ('Engenharia', 'Engenharia'), ('Ciência', 'Ciência')], default='--', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='agente',
            name='curso',
            field=models.CharField(default='--', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agente',
            name='nip',
            field=models.CharField(blank=True, default='--', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='agente',
            name='nivel_academico',
            field=models.CharField(choices=[('9ªClasse', '9ª Classe'), ('12ªClasse', '12ª Classe'), ('13ªClasse', '13ª Classe'), ('Licenciado', 'Licenciado'), ('Mestre', 'Mestre'), ('Doutor', 'Doutor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='baixa',
            name='data_entrada',
            field=models.CharField(default=datetime.date(2019, 5, 15), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='despromocao',
            name='suspensao',
            field=models.CharField(choices=[('outro', 'outro'), ('1 Ano de Cadeia', '1 Ano de Cadeia'), ('1 Mes de Cadeia', '1 Mes de Cadeia'), ('Retirada da Patente', 'Retirada da Patente'), ('2 Mes de Cadeia', '2 Mes de Cadeia'), ('2 Ano de Cadeia', '2 Ano de Cadeia'), ('3 Mes de Cadeia', '3 Mes de Cadeia'), ('Prestar serviço de Limpeza', 'Prestar serviço de Limpeza')], max_length=500),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='data_colocacao',
            field=models.CharField(blank=True, default=datetime.date(2019, 5, 15), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patentiamento',
            name='data',
            field=models.CharField(default=datetime.date(2019, 5, 15), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='casa_numero',
            field=models.CharField(default='--', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome_mae',
            field=models.CharField(blank=True, default='--', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome_pai',
            field=models.CharField(blank=True, default='--', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reforma',
            name='data',
            field=models.CharField(default=datetime.date(2019, 5, 15), max_length=10, null=True),
        ),
    ]
