# Generated by Django 2.2.1 on 2019-05-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal_quadro', '0044_auto_20190515_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='area_formacao',
            field=models.CharField(default='--', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='despromocao',
            name='suspensao',
            field=models.CharField(choices=[('Prestar serviço de Limpeza', 'Prestar serviço de Limpeza'), ('2 Ano de Cadeia', '2 Ano de Cadeia'), ('2 Mes de Cadeia', '2 Mes de Cadeia'), ('3 Mes de Cadeia', '3 Mes de Cadeia'), ('Retirada da Patente', 'Retirada da Patente'), ('outro', 'outro'), ('1 Ano de Cadeia', '1 Ano de Cadeia'), ('1 Mes de Cadeia', '1 Mes de Cadeia')], max_length=500),
        ),
    ]
