# Generated by Django 2.2.1 on 2019-05-16 01:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal_quadro', '0045_auto_20190515_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agente',
            name='funcao',
        ),
        migrations.AlterField(
            model_name='agente',
            name='curso',
            field=models.CharField(default='--', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='baixa',
            name='data_entrada',
            field=models.CharField(default=datetime.date(2019, 5, 16), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='despromocao',
            name='suspensao',
            field=models.CharField(choices=[('2 Ano de Cadeia', '2 Ano de Cadeia'), ('3 Mes de Cadeia', '3 Mes de Cadeia'), ('2 Mes de Cadeia', '2 Mes de Cadeia'), ('1 Mes de Cadeia', '1 Mes de Cadeia'), ('outro', 'outro'), ('Prestar serviço de Limpeza', 'Prestar serviço de Limpeza'), ('Retirada da Patente', 'Retirada da Patente'), ('1 Ano de Cadeia', '1 Ano de Cadeia')], max_length=500),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='data_colocacao',
            field=models.CharField(blank=True, default=datetime.date(2019, 5, 16), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patentiamento',
            name='data',
            field=models.CharField(default=datetime.date(2019, 5, 16), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='provincia',
            field=models.CharField(choices=[('Luanda', 'Luanda'), ('Bengo', 'Bengo'), ('Benguela', 'Benguela'), ('Bié', 'Bié'), ('Cabinda', 'Cabinda'), ('Cunene', 'Cunene'), ('Huambo', 'Huambo'), ('Huila', 'Huila'), ('Cuando Cubango', 'Cuando Cubango'), ('Cuanza Norte', 'Cuanza Norte'), ('Cuanza Sul', 'Cuanza Sul'), ('Lunda Norte', 'Lunda Norte'), ('Lunda Sul', 'Lunda Sul'), ('Malanje', 'Malanje'), ('Moxico', 'Moxico'), ('Namibe', 'Namibe'), ('Uige', 'Uige'), ('Zaire', 'Zaire')], max_length=25),
        ),
        migrations.AlterField(
            model_name='reforma',
            name='data',
            field=models.CharField(default=datetime.date(2019, 5, 16), max_length=10, null=True),
        ),
    ]
