# Generated by Django 2.2.1 on 2019-07-03 16:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal_quadro', '0049_auto_20190613_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Falecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='pessoal_quadro.Baixa')),
                ('cimiteiro', models.CharField(default='--', max_length=50, null=True)),
                ('numero_campa', models.CharField(default='--', max_length=5, null=True)),
                ('data_enterro', models.CharField(default=datetime.date(2019, 7, 3), max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='baixa',
            name='data_entrada',
            field=models.CharField(default=datetime.date(2019, 7, 3), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='despromocao',
            name='suspensao',
            field=models.CharField(choices=[('outro', 'outro'), ('1 Mes de Cadeia', '1 Mes de Cadeia'), ('1 Ano de Cadeia', '1 Ano de Cadeia'), ('Retirada da Patente', 'Retirada da Patente'), ('Prestar serviço de Limpeza', 'Prestar serviço de Limpeza'), ('3 Mes de Cadeia', '3 Mes de Cadeia'), ('2 Ano de Cadeia', '2 Ano de Cadeia'), ('2 Mes de Cadeia', '2 Mes de Cadeia')], max_length=500),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='data_colocacao',
            field=models.CharField(blank=True, default=datetime.date(2019, 7, 3), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patentiamento',
            name='data',
            field=models.CharField(default=datetime.date(2019, 7, 3), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reforma',
            name='data',
            field=models.CharField(default=datetime.date(2019, 7, 3), max_length=10, null=True),
        ),
    ]
