# Generated by Django 2.2.1 on 2019-07-04 01:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal_quadro', '0050_auto_20190703_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='falecimento',
            name='agente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='pessoal_quadro.Agente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baixa',
            name='data_entrada',
            field=models.CharField(default=datetime.date(2019, 7, 4), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='despromocao',
            name='suspensao',
            field=models.CharField(choices=[('2 Mes de Cadeia', '2 Mes de Cadeia'), ('outro', 'outro'), ('Retirada da Patente', 'Retirada da Patente'), ('Prestar serviço de Limpeza', 'Prestar serviço de Limpeza'), ('1 Ano de Cadeia', '1 Ano de Cadeia'), ('1 Mes de Cadeia', '1 Mes de Cadeia'), ('3 Mes de Cadeia', '3 Mes de Cadeia'), ('2 Ano de Cadeia', '2 Ano de Cadeia')], max_length=500),
        ),
        migrations.AlterField(
            model_name='falecimento',
            name='data_enterro',
            field=models.CharField(default=datetime.date(2019, 7, 4), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='data_colocacao',
            field=models.CharField(blank=True, default=datetime.date(2019, 7, 4), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patentiamento',
            name='data',
            field=models.CharField(default=datetime.date(2019, 7, 4), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reforma',
            name='data',
            field=models.CharField(default=datetime.date(2019, 7, 4), max_length=10, null=True),
        ),
    ]
