# Generated by Django 2.2.4 on 2020-06-14 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal_quadro', '0051_auto_20190704_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baixa',
            name='data_entrada',
            field=models.CharField(default=datetime.date(2020, 6, 14), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='despromocao',
            name='suspensao',
            field=models.CharField(choices=[('3 Mes de Cadeia', '3 Mes de Cadeia'), ('Retirada da Patente', 'Retirada da Patente'), ('1 Mes de Cadeia', '1 Mes de Cadeia'), ('2 Ano de Cadeia', '2 Ano de Cadeia'), ('Prestar serviço de Limpeza', 'Prestar serviço de Limpeza'), ('1 Ano de Cadeia', '1 Ano de Cadeia'), ('2 Mes de Cadeia', '2 Mes de Cadeia'), ('outro', 'outro')], max_length=500),
        ),
        migrations.AlterField(
            model_name='falecimento',
            name='data_enterro',
            field=models.CharField(default=datetime.date(2020, 6, 14), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='data_colocacao',
            field=models.CharField(blank=True, default=datetime.date(2020, 6, 14), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patentiamento',
            name='data',
            field=models.CharField(default=datetime.date(2020, 6, 14), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=12),
        ),
        migrations.AlterField(
            model_name='reforma',
            name='data',
            field=models.CharField(default=datetime.date(2020, 6, 14), max_length=10, null=True),
        ),
    ]
