# Generated by Django 2.1.1 on 2018-11-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='categoria',
            field=models.CharField(choices=[('Guia de Marcha', 'Guia de Marcha'), ('Mensagem', 'Mensagem'), ('Plano de Trabalho', 'Plano de Trabalho'), ('Officios', 'Officios'), ('Mapas', 'Mapas'), ('Declarções', 'Declarções'), ('Informações', 'Informações'), ('Propostas', 'Propostas'), ('Actas', 'Actas'), ('Relatorios', 'Relatorios'), ('Diversos', 'Diversos')], max_length=60),
        ),
    ]
