# Generated by Django 2.1.1 on 2018-11-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacao', '0002_auto_20181121_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('um', models.FileField(blank=True, null=True, upload_to='arquivos/%Y/')),
                ('dois', models.FileField(blank=True, null=True, upload_to='arquivos/%Y/')),
            ],
        ),
    ]
