# Generated by Django 2.1.1 on 2018-12-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacao', '0003_imagam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagam',
            name='dois',
            field=models.FileField(blank=True, null=True, upload_to='%Y/'),
        ),
        migrations.AlterField(
            model_name='imagam',
            name='um',
            field=models.FileField(blank=True, null=True, upload_to='%Y/'),
        ),
    ]
