# Generated by Django 2.1.1 on 2018-12-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacao', '0004_auto_20181204_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagam',
            name='dois',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='imagam',
            name='um',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
