# Generated by Django 2.1.1 on 2018-12-26 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentacao', '0005_auto_20181204_0316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['-id']},
        ),
    ]
