# Generated by Django 2.1.1 on 2018-12-26 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentacao', '0006_auto_20181226_0032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['id']},
        ),
    ]
