# Generated by Django 2.1.1 on 2018-12-27 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentacao', '0007_auto_20181226_0035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['-id']},
        ),
    ]
