# Generated by Django 2.1.1 on 2019-01-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacao', '0008_auto_20181227_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='categoria',
            field=models.CharField(choices=[('Guia de Marcha', 'Guia de Marcha'), ('Mensagem', 'Mensagem'), ('Plano de Trabalho', 'Plano de Trabalho'), ('Officios', 'Officios'), ('Mapas', 'Mapas'), ('Declarações', 'Declarações'), ('Informações', 'Informações'), ('Propostas', 'Propostas'), ('Actas', 'Actas'), ('Relatórios', 'Relatórios'), ('Diversos', 'Diversos')], max_length=60),
        ),
    ]
