# Generated by Django 2.2.1 on 2019-05-08 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentacao', '0009_auto_20190130_1634'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagam',
        ),
    ]
