# Generated by Django 2.1.1 on 2019-01-30 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferencia', '0009_auto_20181227_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_entrada',
            field=models.CharField(default=datetime.date(2019, 1, 30), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='data',
            field=models.CharField(default=datetime.date(2019, 1, 30), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='troca',
            name='data',
            field=models.CharField(default=datetime.date(2019, 1, 30), max_length=20, null=True),
        ),
    ]
