# Generated by Django 2.1.1 on 2019-02-06 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferencia', '0010_auto_20190130_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_entrada',
            field=models.CharField(default=datetime.date(2019, 2, 6), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='data',
            field=models.CharField(default=datetime.date(2019, 2, 6), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='troca',
            name='data',
            field=models.CharField(default=datetime.date(2019, 2, 6), max_length=20, null=True),
        ),
    ]
