# Generated by Django 2.1.1 on 2019-02-14 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferencia', '0012_auto_20190213_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='agente',
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='data',
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='orgao_origem',
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='transferencia/%Y/'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='motivo',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='troca',
            name='data',
            field=models.CharField(default=datetime.date(2019, 2, 14), max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
