# Generated by Django 2.1.1 on 2019-02-18 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferencia', '0014_auto_20190214_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='troca',
            name='destino_segundo',
        ),
        migrations.RemoveField(
            model_name='troca',
            name='origem_segundo',
        ),
        migrations.AlterField(
            model_name='troca',
            name='data',
            field=models.CharField(default=datetime.date(2019, 2, 18), max_length=20, null=True),
        ),
    ]
