# Generated by Django 2.1.1 on 2019-02-21 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferencia', '0017_auto_20190219_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troca',
            name='data',
            field=models.CharField(default=datetime.date(2019, 2, 21), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='troca',
            name='destino_segundo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='troca',
            name='origem_segundo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
