# Generated by Django 2.1.1 on 2019-02-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferencia', '0018_auto_20190221_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='numero_guia',
            field=models.CharField(default=0, max_length=10, null=True),
        ),
    ]
