# Generated by Django 2.1.1 on 2019-02-22 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferencia', '0019_transferencia_numero_guia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troca',
            name='data',
            field=models.CharField(default=datetime.date(2019, 2, 22), max_length=20, null=True),
        ),
    ]
