# Generated by Django 2.1.1 on 2019-05-01 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferencia', '0020_auto_20190222_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troca',
            name='data',
            field=models.CharField(default=datetime.date(2019, 5, 1), max_length=20, null=True),
        ),
    ]
