# Generated by Django 2.2.1 on 2019-05-08 00:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferencia', '0022_auto_20190504_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troca',
            name='data',
            field=models.CharField(default=datetime.date(2019, 5, 8), max_length=20, null=True),
        ),
    ]
