# Generated by Django 2.2.1 on 2019-05-15 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferencia', '0023_auto_20190508_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troca',
            name='data',
            field=models.CharField(default=datetime.date(2019, 5, 15), max_length=20, null=True),
        ),
    ]
