# Generated by Django 2.2.1 on 2019-06-13 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferencia', '0025_auto_20190516_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='situacao',
            field=models.CharField(default='Espera', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='dispacho',
            field=models.CharField(default='Sem dispacho', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='troca',
            name='data',
            field=models.CharField(default=datetime.date(2019, 6, 13), max_length=20, null=True),
        ),
    ]
