# Generated by Django 2.2.1 on 2019-07-03 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferencia', '0026_auto_20190613_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troca',
            name='data',
            field=models.CharField(default=datetime.date(2019, 7, 3), max_length=20, null=True),
        ),
    ]
