# Generated by Django 2.2.1 on 2019-07-04 01:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferencia', '0027_auto_20190703_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troca',
            name='data',
            field=models.CharField(default=datetime.date(2019, 7, 4), max_length=20, null=True),
        ),
    ]
