# Generated by Django 2.1.1 on 2018-09-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastro', models.CharField(max_length=100)),
                ('atualizar', models.CharField(max_length=100)),
                ('eliminar', models.CharField(max_length=100)),
                ('listar', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=20)),
            ],
        ),
    ]
