# Generated by Django 2.1.1 on 2018-11-15 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formacao_conclusao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='pessoal_quadro.Agente')),
                ('curso', models.CharField(max_length=100)),
                ('dispacho', models.CharField(blank=True, default='Sem dispacho', max_length=20, null=True)),
                ('aproveitamento', models.CharField(blank=True, choices=[('', 'Aproveitamento'), ('Desistente', 'desistente'), ('Reprovado', 'reprovado'), ('Aprovado', 'aprovado')], default='Não avaliado', max_length=40, null=True)),
                ('data_conclusao', models.CharField(max_length=20)),
                ('comprovativo', models.FileField(blank=True, default='sem nenhum justificativo', null=True, upload_to='formacao/%Y/')),
            ],
        ),
        migrations.CreateModel(
            name='Selecionado_formacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='pessoal_quadro.Agente')),
                ('curso', models.CharField(max_length=100)),
                ('dispacho', models.CharField(blank=True, default='Sem dispacho', max_length=20, null=True)),
                ('data', models.CharField(max_length=20)),
            ],
        ),
    ]
