# Generated by Django 2.1.1 on 2018-11-15 04:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='pessoal_quadro.Agente')),
                ('selecionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='formacao.Selecionado_formacao')),
                ('data', models.CharField(default=datetime.date(2018, 11, 15), max_length=20, null=True)),
            ],
        ),
    ]
