# Generated by Django 2.1.1 on 2018-11-21 01:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacao', '0002_presenca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formacao_conclusao',
            name='aproveitamento',
            field=models.CharField(blank=True, choices=[('Desistente', 'desistente'), ('Reprovado', 'reprovado'), ('Aprovado', 'aprovado')], default='Não avaliado', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='presenca',
            name='data',
            field=models.CharField(default=datetime.date(2018, 11, 21), max_length=20, null=True),
        ),
    ]
