# Generated by Django 2.1.1 on 2018-11-24 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacao', '0003_auto_20181121_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenca',
            name='data',
            field=models.CharField(default=datetime.date(2018, 11, 24), max_length=20, null=True),
        ),
    ]
