# Generated by Django 2.1.1 on 2018-12-04 02:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacao', '0006_auto_20181130_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenca',
            name='data',
            field=models.CharField(default=datetime.date(2018, 12, 4), max_length=20, null=True),
        ),
    ]
