# Generated by Django 2.1.1 on 2019-02-13 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacao', '0012_auto_20190206_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenca',
            name='data',
            field=models.CharField(default=datetime.date(2019, 2, 13), max_length=20, null=True),
        ),
    ]
