# Generated by Django 2.1.1 on 2019-02-14 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacao', '0013_auto_20190213_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenca',
            name='data',
            field=models.CharField(default=datetime.date(2019, 2, 14), max_length=20, null=True),
        ),
    ]
