# Generated by Django 2.1.1 on 2019-02-18 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacao', '0014_auto_20190214_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenca',
            name='data',
            field=models.CharField(default=datetime.date(2019, 2, 18), max_length=20, null=True),
        ),
    ]
