# Generated by Django 2.1.1 on 2019-02-19 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacao', '0015_auto_20190218_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenca',
            name='data',
            field=models.CharField(default=datetime.date(2019, 2, 19), max_length=20, null=True),
        ),
    ]
