# Generated by Django 2.1.1 on 2019-02-22 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacao', '0019_auto_20190222_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selecionado_formacao',
            name='data',
            field=models.CharField(default=datetime.date(2019, 2, 22), max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='selecionado_formacao',
            name='pais',
            field=models.CharField(choices=[(' ', ' '), ('Africa do Sul', 'Africa do Sul'), ('Afeganistão', 'Afeganistão'), ('Albânia', 'Albânia'), ('Alemanha', 'Alemanha'), ('Andorra', 'Andorra'), ('Argélia', 'Argélia'), ('Argentina', 'Argentina'), ('Austrália', 'Austrália'), ('Bélgica', 'Bélgica'), ('Bolívia', 'Bolívia'), ('Brasil', 'Brasil'), ('Botsuana', 'Botsuana'), ('Cabo Verde', 'Cabo Verde'), ('Canada', 'Canada'), ('China', 'China'), ('Costa Rica', 'Costa Rica'), ('cuba', 'cuba'), ('Espanha', 'Espanha'), ('Estados Unidos', 'Estados Unidos'), ('França', 'França'), ('Gabão', 'Gabão'), ('Grécia', 'Grécia'), ('Holanda', 'Holanda'), ('Russia', 'Russia')], default='Angola', max_length=100, null=True),
        ),
    ]
