# Generated by Django 2.1.1 on 2019-05-01 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacao', '0021_formacao_conclusao_instituicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formacao_conclusao',
            name='dispacho',
            field=models.CharField(blank=True, default='Sem despacho', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='presenca',
            name='data',
            field=models.CharField(default=datetime.date(2019, 5, 1), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='selecionado_formacao',
            name='data',
            field=models.CharField(default=datetime.date(2019, 5, 1), max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='selecionado_formacao',
            name='dispacho',
            field=models.CharField(blank=True, default='Sem despacho', max_length=20, null=True),
        ),
    ]
