from django.urls import path
from . import views

app_name = 'pessoal_quadro'
urlpatterns = [
    path('cadastrar/', views.cadastrar, name='cadastrar'),
    path('area_pessoal_quadro/', views.area_pessoal_quadro, name='area-pessoal-quadro'),
    path('consultar_dados/', views.consultar_dados, name='consultar-dados'),
    path('imprimir_informacao/', views.imprimir_informacao, name='imprimir-informacao'),
    path('listar_todos_agente/', views.listar_todos_agente, name='listar-todos'),
    path('registar_baixa/', views.registar_baixa, name='registar-baixa'),
    path('listar_baixas/', views.listarBaixas, name='listar-baixas'),
    path('registar_despromocao/', views.registar_despromocao, name='registar-despromocao'),
    #path('listar_despromocao/', views.listarDespromocao, name='listar-despromocao'),
    path('listar_reforma/', views.listarReforma, name='listar-reforma'),
    path('listar_nomiacao/', views.listar_nomiacao, name='listar-nomiacao'),
    path('listar_tempo_efetividade/', views.listar_tempo_efetividade, name='listar-efetividade'),
    path('editar_cadastro/<int:id>/', views.editar_cadastro, name='editar-cadastro'),
    path('informacao_pessoal/<int:id>/', views.informacao_pessoal, name='informacao-pessoal'),
    path('editarDados_baixas/<int:id>/', views.editarDados_baixas, name='editar-baixas'),
    #path('atualizar_despromocao/<int:id>/', views.atualizar_despromocao, name='atualizar-despromocao'),
    #path('editar_feria/<int:id>/', views.editar_ferias, name='editar-feria'),
    path('editar_dados_nomiacao/<int:id>/', views.editar_nomiacao, name='editar-dados-nomiacao'),
    #path('remover_despromocao/', views.remover_despromocao, name='remover-despromocao'),
    path('eliminar_nomiacao/', views.eliminar_nomiacao, name='eliminar-nomiacao'),
    path('eliminar_baixa/', views.eliminar_baixa, name='eliminar-baixa'),
    path('efectuar_colocacao/', views.efectuar_Colocacao, name='efectuar-colocacao'),
    path('registar_nomiacao/', views.registar_nomiacao, name='registar-nomiacao'),
    path('registar_reforma/', views.registar_reforma_anticipada, name='registar-reforma'),
    path('atualizar_patente/', views.atualizar_patente, name='atualizar-patente'),
    #path('gerar-codigo/', views.gerar_codigo_seguranca, name='gerar-codigo'),
    path('codigo_cadastrar/', views.codigo_cadastrar, name='codigo-cadastrar'),
    #path('codigo_validar_despromocao/', views.codigo_validar_despromocao, name='codigo-validar-despromocao'),
    path('ficha_pessoal/<int:id>/', views.ficha_pessoal, name='ficha-pessoal'),
    path('registar_documento/', views.registar_documentos, name='documento'),
    path('registar_Processo_displinar/', views.registar_processoDisciplinar, name='Processo-displinar'),
    path('listar_documentos/',  views.listar_documentos, name='listar-docs'),
    path('consultar_docs/',  views.consultar_documentos, name='consultar-docs'),
    path('listar_disciplina/', views.listar_processoDisciplinar, name='listar-disciplina'),
    path('processo_disciplinar_informacao/<int:id>/', views.informacao_processo_disciplinar, name='pessoal-informacao'),
    path('eliminar_processo_disciplinar/', views.eliminar_processoDiciplinar, name='eliminar-processo'),
    path('consultar_processo_disciplinar/', views.consultar_processo_disciplinar, name='consultar-processo'),
    path('eliminar_reforma_anticipada/', views.eliminar_reforma_anticipada, name='eliminar-reforma'),
    path('ficha_processo_disciplinar/<int:id>/', views.ficha_processo_disciplinar, name='ficha-processo'),
    path('retorna_cursos/', views.retorna_cursos, name='retorna-cursos'),
    path('retorna_municipio/', views.retorna_municipio, name='retorna-municipio'),
    path('listar_falecimento/', views.listar_falecimento, name='listar-falecidos'),
    
    #path('consultar_dados_atualizar/', views.consultar_dados_atualizar, name='consultar-atualizar'),
]
